#!/bin/bash

pallette="0 '#000090', 1 '#000fff', 2 '#0090ff',\
	3 '#0fffee', 4 '#90ff70', 5 '#ffee00',\
	6 '#ff7000', 7 '#ee0000', 8 '#7f0000'"

gnuplot --persist <<- EOP
	reset

	set autoscale fix
	set palette defined ($pallette)
	set xlabel 'Seconds'
	set ylabel 'Frequency band'
	set xtics ($3)
	set title '$2'
	unset colorbox

	plot '$1' matrix with image
EOP
